### ISSUE TITLE
Najít poslední verzi FW

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/LABDOS01#1]
Firmware pro starší/existující varianty spacedosů zřejmě existuje ve více variantách. Obvykle podle specifik konkrétních aplikací. Je potřeba najít nejpodobnější/nejaktuálnější verzi posledního FW a přidat ji do tohoto repozitáře. Aby z ní šlo dále vycházet.

**Comment by kaklik** [comment]
Tohle asi nejpravděpodobněji dovede vyřešit @kakl

**Comment by kakl** [comment]
Potrebujete FW pro Resetitko.

**Comment by kaklik** [comment]
> Potrebujete FW pro Resetitko.

A ten je kde? Tady jsem sice našel [repozitář resetítka](https://github.com/ODZ-UJF-AV-CR/resetitko) ale i tak není jasné, který FW je aktuální.

**Comment by roman-dvorak** [comment]
Byl vybrán FW, který byl naposled editovaný. Je přidaný do tohoto repozitáře. 
https://github.com/ODZ-UJF-AV-CR/resetitko/tree/main/resetitko16Mhz
