### ISSUE TITLE
Automatická kompilace firmware pro SPACEDOS03

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/LABDOS01#2]
Pro github actions existuje [compile-arduino-sketches](https://github.com/marketplace/actions/compile-arduino-sketches) worker, který by měl umět zkompilovat arduino projekt a vytvořit soubor, který by měl jít nahrát do arduino spacedosu.

**Comment by kaklik** [comment]
Tohle vypadá, že je nyní vyřešeno tímto: https://github.com/UniversalScientificTechnologies/SPACEDOS03/tree/SPACEDOS03A/.github/workflows
