### ISSUE TITLE
Verze firmware zjistitelná z fungující instance

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/LABDOS01#3]
Bylo by velmi přinosné, aby bylo možné zjistit, jaký commit firmware aktuálně běží. 

Obvykle se to řeši tak, že se nějakým způsobem vygeneruje soubor (např. git_version.h), který bude obsahovat definici aktuálního commitu. S výhodou může tento soubor obsahovat arduino makra vkládající aktuální datum a čas pro lokální kompilování - tím půjde poznat, jestli to bylo kompilované v CI nebo jestli to bylo kompilované v uživatelském počítači. 

Soubor git_version.h může být vytvořen buď v rámci samotného CI nebo nějakým arduino pre-compile skriptem. To ale nevím, jestli funguje i s CI nástrojem. 

Po spuštění firmware může být aktuální verze (+ nějaké nastavení) vypsána po sériovce.

**Comment by kaklik** [comment]
Není tohle už v aktuálním firmware dostatečně vyřešeno? 
Třeba na [tomto řádku](https://github.com/UniversalScientificTechnologies/LABDOS01/blob/64c51e8f8a99e59f89b101223a6cc948b15df7a1/fw/LABDOS/LABDOS.ino#L197) vidím výpis něčeho jako FWversion.
