### ISSUE TITLE
Typo in bottom box sticker

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/LABDOS01#5]
There is accidentally [silicone](https://en.wikipedia.org/wiki/Silicone) instead of [silicon](https://en.wikipedia.org/wiki/Silicon): 

![image](https://user-images.githubusercontent.com/1194177/181245555-f3df1f7f-e418-42c5-b000-f4ca30a70442.png)

At the same time, I suggest updating the text to describe better form: "LABDOS01 is an open-source spectrometer-dosimeter based on silicon PIN diode and is intended for scientific research and experimental purposes. "

**Comment by roman-dvorak** [comment]
V návrhu samolepek opraveno:

![obrazek](https://user-images.githubusercontent.com/5196729/192254842-ef3a9ac8-585d-463b-89fd-a06d50d35ec1.png)

Zároveň vyretušováno na všech fotkách v repozitáři.
